### ISSUE TITLE
Issue when I'm logging via Hugging Face CLI

### ISSUE THREAD

**Issue by svrebelo-eth** [jossalgon/StableDiffusionTelegram#7]
Hey guys! I've been trying to reproduce the steps but after creating an account and generating the Token in Hugging Face, once I've paste the Token I get the following error:

`Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\huggingface-cli.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\huggingface_hub\commands\huggingface_cli.py", line 45, in main
    service.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\huggingface_hub\commands\user.py", line 149, in run
    _login(self._api, token=token)
  File "C:\ProgramData\Anaconda3\lib\site-packages\huggingface_hub\commands\user.py", line 320, in _login
    hf_api.set_access_token(token)
  File "C:\ProgramData\Anaconda3\lib\site-packages\huggingface_hub\hf_api.py", line 719, in set_access_token
    write_to_credential_store(USERNAME_PLACEHOLDER, access_token)
  File "C:\ProgramData\Anaconda3\lib\site-packages\huggingface_hub\hf_api.py", line 588, in write_to_credential_store
    with subprocess.Popen(
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified`

Any ideas what this could be?

Thanks in advance

**Comment by svrebelo-eth** [comment]
More details:
- Windows Server 2019 (VPS)
- I've installed the Anaconda Package for Windows and followed the steps
